rootProject.name = "netty-rpc"

include("core")
include("client")
include("server")
include("opentelemetry")
include("spring-boot-starter-server")
include("spring-boot-starter-client")
include("spring-boot-starter-opentelemetry")
include("example:helloworld")
include("example:sdk")
include("example:register")
include("example:opentelemetry-example")
include("example:springboot-server")
include("example:springboot-client")