// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/src/main/resources/hello-service.proto

package io.github.helloworlde.netty.protobuf.proto;

public final class HelloServiceProto {
  private HelloServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_helloworlde_netty_protobuf_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_helloworlde_netty_protobuf_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_helloworlde_netty_protobuf_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_helloworlde_netty_protobuf_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/protobuf/src/main/resources/hello-serv" +
      "ice.proto\022$io.github.helloworlde.netty.p" +
      "rotobuf\">\n\014HelloRequest\022\n\n\002id\030\001 \001(\003\022\017\n\007m" +
      "essage\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\"?\n\rHello" +
      "Response\022\n\n\002id\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\022\021\n" +
      "\ttimestamp\030\003 \001(\003BA\n*io.github.helloworld" +
      "e.netty.protobuf.protoB\021HelloServiceProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_helloworlde_netty_protobuf_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_helloworlde_netty_protobuf_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_helloworlde_netty_protobuf_HelloRequest_descriptor,
        new java.lang.String[] { "Id", "Message", "Timestamp", });
    internal_static_io_github_helloworlde_netty_protobuf_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_helloworlde_netty_protobuf_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_helloworlde_netty_protobuf_HelloResponse_descriptor,
        new java.lang.String[] { "Id", "Message", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
